export enum AppRoute {
  //Top Level
  PRIMARY_STACK = 'primary stack',
  MAIN = 'MAIN',
  MAIN_TABS = 'Main Tabs',
  NESTED = 'NESTED',
  //Auth= 'Auth',
  AUTH_FLOW = 'Auth',
  SIGN_IN_CONFIRM_CODE = 'SIGN_IN_CONFIRM_CODE',
  SIGN_UP = 'SIGN_UP',
  RESET_PASSWORD = 'RESET_PASSWORD',
  LOGOUT = 'LOGOUT',
  CONSUMER_ONBOARDING = 'onboarding',

  LOGIN = 'login',
  FORGOT_PASSWORD = 'forgot password',
  CHANGE_PASSWORD = 'change password',
  PASSWORD_CHANGED = 'password changed',
  PHONE_INPUT = 'phone input',

  MAP = 'Map',
  MAP_LIST_VIEW = 'Map List',
  MAP_NAVIGATOR = 'Map Navigator Stack',
  FEED = 'FEED',
  CONSUMER_PROFILE = 'CONSUMER_PROFILE',
  NOTIFICATIONS = 'NOTIFICATIONS',
  MESSAGING = 'MESSAGING',
  MORE = 'MORE',

  SEARCH = 'Search',
  CREATE_POST = 'Create Post',
  MY_POSTS = 'My Posts',
  POST_DETAILS = 'Post Details',
  POST_SHOW_ALL = 'Show all posts',
  FEED_ONBOARDING = 'Select Interests',
  ALERTS = 'Alerts',
  MY_PROFILE = 'My Profile',
  MY_SETTINGS = 'Settings',
  MY_FAVORITES = 'My favorites',
  FOLLOWING = 'Following',
  CREATE_CHAT = 'New Chat',
  CHAT_LIST = 'Chats',
  CHAT_DETAILS = 'Chat Details',

  ABOUT = 'ABOUT',
  WELCOME = 'WELCOME',
  SETTINGS = 'SETTINGS',
  ADD_CONTACT = 'ADD_CONTACT',
  NOTIFICATION_CENTER = 'NOTIFICATION_CENTER',
}
